name: dcc
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.3
  - ipython=8.15.0
  - ipywidgets=8.1.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.10
  - matplotlib-inline=0.1.6
  - pip=23.3.1
  - python=3.9.19
  - pandas=1.4.2
  - matplotlib=3.5.1
  - pip:
    - lightgbm==4.3.0
    - numpy==1.26.4
    - scipy==1.13.0
